name: Simple Bash Workflow

on:
    push:
        branches:
            - check-test
    pull_request:

jobs:
    bash-example:
        runs-on: ubuntu-latest
        steps:
            - name: Teste 02
              run: |
                expected_files_count=52
                actual_files_count=$(find . \( -path './participantes' -o -path './.git' -o -path './.github' \)  -prune -o -print | wc -l)
                if [ $expected_files_count -ne $actual_files_count ]; then
                    echo "Arquivos removidos ou adicionados fora do diret√≥rio permitido."
                    exit 1
                fi
                